[package]
name = "csc_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = { workspace = true }
vulkano-util = { workspace = true }
egui_winit_vulkano = { workspace = true }
vulkano-shaders = "0.34.0"
png = "0.17.10"
cgmath = { workspace = true }
