[package]
name = "csc_core"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = { workspace = true }
ecolor = { workspace = true }
egui_node_graph = { workspace = true }
anyhow = { workspace = true }