[package]
name = "csc_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.21.0"
egui = "0.21.0"
egui_node_graph = { git = "https://github.com/setzer22/egui_node_graph.git" }
anyhow = "1.0"
serde = { version = "1.0", optional = true }

[features]
default = []
persistence = ["serde", "egui_node_graph/persistence", "eframe/persistence"]